---
title:  "Spring 공부하며 발생한 오류들"
excerpt: "이런저런 오류들에 대한 해결방법"
date:   2021-09-12 11:03:00 +0900

categories: javaSpring
tags:
  - Java
  - Spring
  - 오류
  - error
last_modified_at: 2021-09-15T01:47:00-05:00


---

<br/>

<br/>

<br/>

### 1.  Removing a detached instance 

에러 메세지는 다음과 같았다.

**caused by java.lang.illegalargumentexception: Removing a detached instance**

오류의 원인은 이미 Detached 시킨 엔티티를 remove 하려 시도했기 때문이란다.

Hibernate는 트렌젝션이 끝나거나, em.detach(entity); 를 하면 영속성 컨텍스트에서 해당 엔티티를 관리하지 않는데, 이미 detach를 시킨(즉 영속성 컨텍스트가 관리하고 있지 않은 준영속 상태의) entity를 remove 하려 했기때문에 난 에러이다.

![image-20210914001901176](https://raw.githubusercontent.com/ShinDongHun1/image_repo/main/img/image-20210914001901176.png)

오류가 난 코드는 다음과 같았다. 다음부터는 준영속 상태의 엔티티를 remove 하려 시도하지 말자 ㅎ

<br/>

<br/>

#### 2. ERROR: HHH000099: an assertion failure occured (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session): org.hibernate.AssertionFailure: possible non-threadsafe access to session

전체 메세지는 다음과 같다

ERROR: HHH000099: an assertion failure occurred (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session): org.hibernate.AssertionFailure: possible non-threadsafe access to session

Exception in thread "main" javax.persistence.RollbackException: Error while committing the transaction

Caused by: org.hibernate.AssertionFailure: possible non-threadsafe access to session

후... 이게 날 진짜 골땡이 아프게 했다. 일단 오류난 코드는 이러하다

![image-20210915003947818](https://raw.githubusercontent.com/ShinDongHun1/image_repo/main/img/image-20210915003947818.png)

다음은 오류 메세지이다

<img src="https://raw.githubusercontent.com/ShinDongHun1/image_repo/main/img/image-20210915005242431.png" alt="image-20210915005242431"  />

후.... 이게 무슨 일일까.. 였다.

내가 배운 바로는 persist를 하면 영속성 컨텍스트에 저장되고,  detach를 하면 영속성 컨텍스트에서 지워지고, 따라서 1차캐시에서도 지워진다. 근데 웃긴게 위 코드를 보면, persist(member1), persist(member2) ,detach(member1) 을 순서대로 해줬는데, 내가 배운대로라면 member1과 member2를 1차 캐시에 넣고, 그 이후에 member1을 1차캐시에서 제거해야 한다. 저상태로 커밋하면 아직 1차캐시에는 member2는 존재하므로 데이터베이스에는 member2가 저장되었어야 한다고 생각했는데, 오류가 발생했다. 

<br/>

메세지는

**an assertion failure occured** :어썰션(확인) 실패가 발생했다?

**this may indicate a bug in Hibernate**: 이것은 hibernate의 버그일 수 있습니다.

**but is more likely due to unsafe use of the session**: 그러나 세션의 안전하지 않은 사용으로 인해 나타났을 확률이 더 큽니다. 

<br/>

후.. 이걸 보고 나는 당연히 내가 뭘 잘못했겠거니 싶어서, 이것저것 찾아보고 구글링해보고 물어보고 다녔는데 결국 이유를 찾지 못하였다. 나는 인프런에서 김영한 선생님의 강의를 듣고 있는데, 선생님께 질문하여보니 드디어 오늘 답이왔다!!!!

> 이것은 하이버네이트 내부 버그일 가능성이 높습니다.
>
> 오류 메시지를 잘 보시면 다음과 같이 하이버네이트 버그를 나타낼 수 있다는 표현이 있습니다.
>
> HHH000099: an assertion failure occurred (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session)
>
> **실제 detach를 하고 이후에 또 merge를 호출하도록 사용하는 일은 없기 때문에 이 부분은 크게 고민하지 않으셔도 됩니다.**
>
> 참고로 다음에서 flush()를 중간에 호출해주면 정상 동작하는데요. 아마도 하이버네이트 내부 프로세스 이벤트와 관련된 버그로 보입니다.

[출처 - 인프런](https://www.inflearn.com/questions/304787)

그렇단다!!!!! 하이버네이트 내부 버그일 가능성이 높단다!!!! 참.... 슬펐다..... 혹시 나처럼 굉장히 호기심이 많아서 이것저것 뚱땅거리면서 시험해보다 이런 오류를 만났으면... 도움이 됐기를 바란다.

<br/>

참고로 

```
Member member1 = new Member();
Member member2 = new Member();

member1.setId(1L);
member2.setId(2L);

member1.setName("신");
member2.setName("동");
em.persist(member1);

em.flush();//추가

em.persist(member2);
em.detach(member1);

tx.commit();
```

이런 식으로 em.flush()를 추가해주면 정상적으로 잘 작동한다. ㅎ

<br/>

**그러나**

```
em.persist(member2);

em.flush();//추가

em.persist(member1);
em.detach(member1);
```

이런식으로 작성하게 되면.. member2가 flush되어 저장이 될 것 같지만... 오류만 나고 저장되지 않는다고..

참고로 위 코드의 오류내용은 

> ERROR: HHH000099: an assertion failure occurred (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session): org.hibernate.AssertionFailure: possible non-threadsafe access to session
>
> Exception in thread "main" javax.persistence.RollbackException: Error while committing the transaction
>
> Caused by: org.hibernate.AssertionFailure: possible non-threadsafe access to session

으로 위에서 본 에러 메시지와 똑같다

또한 이를 실험하다가 발생한 오류가 있는데 바로 아래에서 다뤄보겠다.

<br/>

<br/>

#### 3. detached entity passed to persist

이 오류에 대해 찾아보았는데 발생하는 상황이 매우 많았다. 

나의 경우에는 

![image-20210915014352884](https://raw.githubusercontent.com/ShinDongHun1/image_repo/main/img/image-20210915014352884.png)

이와 같이 @GeneratedValue가 붙은 변수에

<br/>



![image-20210915014605842](https://raw.githubusercontent.com/ShinDongHun1/image_repo/main/img/image-20210915014605842.png)

```
 member1.setId(1L);
```

이렇게 id값을 지정해버려서 발생하였다. 

@GeneratedValue 를 지우거나

setId를 지워주면 해결된다 ㅎ
